// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;


public class ImportTest {
  private WebDriver driver;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    new HashMap<String, Object>();
  }

  
  @Test
  public void clickOnce() {
    driver.get("http://localhost:8888/clickmebaby.php");
    driver.findElement(By.linkText("Click me baby")).click();
    driver.findElement(By.id("clickMe")).click();
    assertThat(driver.findElement(By.id("clicks")).getText(), is("1"));
    assertThat(driver.findElement(By.cssSelector(".description")).getText(), is("klik"));
  }

  @After
  public void tearDown() {
    driver.quit();
  }
  
}
